
const products = [
  // Baguette Category (20 Products)
  {
    productId: 1,
    categoryIndex: 0,
    productName: 'Rekebaguette',
    unitPrice: 69,
    description: 'En klassisk baguette fylt med ferske reker, majones og smør. Perfekt for sjømatelskere. Allergener: Skalldyr',
    image: 'rekebaguette.webp',
    preorderRequired: true,
    customizationAvailable: true,
    unitsinStock: 10,
  },
  {
    productId: 2,
    categoryIndex: 0,
    productName: 'Kyllingbaguette',
    unitPrice: 79,
    description: 'Baguette med saftig marinert kylling, salat og hvitløksmajones. Allergener: Hvete, Egg',
    image: 'kyllingbaguette.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 15,
  },
  {
    productId: 3,
    categoryIndex: 0,
    productName: 'Vegetarbaguette',
    unitPrice: 54,
    description: 'En sunn baguette med hummus, avokado og grillede grønnsaker. Allergener: Hvete, Soya',
    image: 'vegetarbaguette.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 12,
  },
  {
    productId: 4,
    categoryIndex: 0,
    productName: 'Roastbeefbaguette',
    unitPrice: 74,
    description: 'Baguette med mørt roastbiff, sylteagurk og sennepsmajones. Allergener: Hvete, Sennep',
    image: 'roastbeefbaguette.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 8,
  },
  {
    productId: 5,
    categoryIndex: 0,
    productName: 'Tunfiskbaguette',
    unitPrice: 79,
    description: 'Smakfull baguette fylt med tunfiskrøre, rødløk og salat. Allergener: Fisk, Hvete',
    image: 'tunfiskbaguette.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 10,
  },
  {
    productId: 6,
    categoryIndex: 0,
    productName: 'Skinkebaguette',
    unitPrice: 69,
    description: 'Baguette med fersk skinke, ost og salat. En klassiker til lunsj. Allergener: Melk, Hvete',
    image: 'skinkebaguette.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 20,
  },
  {
    productId: 7,
    categoryIndex: 0,
    productName: 'Egg- og baconbaguette',
    unitPrice: 74,
    description: 'Sprø baguette med egg, sprøstekt bacon og salat. Allergener: Egg, Hvete',
    image: 'egg_baconbaguette.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 18,
  },
  {
    productId: 8,
    categoryIndex: 0,
    productName: 'Brie og avokadobaguette',
    unitPrice: 89,
    description: 'Frisk baguette med kremet brie og moden avokado. Allergener: Melk, Hvete',
    image: 'brie_avokadobaguette.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 14,
  },
  {
    productId: 9,
    categoryIndex: 0,
    productName: 'Falafelbaguette',
    unitPrice: 79,
    description: 'En plantebasert baguette med falafel, tahinisaus og salat. Allergener: Hvete, Sesam',
    image: 'falafelbaguette.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 16,
  },
  {
    productId: 10,
    categoryIndex: 0,
    productName: 'Laks og kremostbaguette',
    unitPrice: 69,
    description: 'Delikat baguette med røkt laks og kremost. Perfekt for fiskelskere. Allergener: Fisk, Melk, Hvete',
    image: 'laks_kremostbaguette.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 12,
  },
  {
    productId: 11,
    categoryIndex: 0,
    productName: 'Capresebaguette',
    unitPrice: 74,
    description: 'En italiensk baguette med mozzarella, tomat, basilikum og balsamico. Allergener: Melk, Hvete',
    image: 'capresebaguette.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 14,
  },
  {
    productId: 12,
    categoryIndex: 0,
    productName: 'Baguette med spekeskinke',
    unitPrice: 69,
    description: 'Klassisk baguette med spekeskinke og smør. Allergener: Hvete, Melk',
    image: 'spekematbaguette.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 15,
  },
  {
    productId: 13,
    categoryIndex: 0,
    productName: 'Egg- og rekebaguette',
    unitPrice: 79,
    description: 'Luksuriøs baguette med egg, reker og majones. Allergener: Skalldyr, Egg, Hvete',
    image: 'egg_rekebaguette.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 12,
  },
  {
    productId: 14,
    categoryIndex: 0,
    productName: 'Biff og løkbaguette',
    unitPrice: 74,
    description: 'Baguette med grillet biff, karamellisert løk og salat. Allergener: Hvete',
    image: 'biff_løkbaguette.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 10,
  },
  {
    productId: 15,
    categoryIndex: 0,
    productName: 'Ribbe- og rødkålbaguette',
    unitPrice: 89,
    description: 'Julestemning i en baguette med ribbe og rødkål. Allergener: Hvete, Melk',
    image: 'ribbe_baguette.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 8,
  },

  // Canapes Category (20 Products)
  {
    productId: 21,
    categoryIndex: 1,
    productName: 'Røkelaks på rugbrød',
    unitPrice: 5.0,
    description: 'Delikat canapé med røkelaks og dill på sprøtt rugbrød. Allergener: Fisk, Hvete',
    image: 'rokelaks_rugbrød.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 30,
  },
  {
    productId: 22,
    categoryIndex: 1,
    productName: 'Miniburger med pulled pork',
    unitPrice: 6.5,
    description: 'Smakfull miniburger med pulled pork og coleslaw. Allergener: Hvete, Egg',
    image: 'miniburger_pulledpork.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 25,
  },
  {
    productId: 23,
    categoryIndex: 1,
    productName: 'Mini quiche med spinat',
    unitPrice: 4.0,
    description: 'Liten quiche fylt med spinat og ost. Allergener: Melk, Hvete, Egg',
    image: 'mini_quiche_spinat.webp',
    preorderRequired: true,
    customizationAvailable: true,
    unitsinStock: 40,
  },
  {
    productId: 24,
    categoryIndex: 1,
    productName: 'Bruschetta med tomat og basilikum',
    unitPrice: 3.5,
    description: 'En klassisk bruschetta med tomat, hvitløk og basilikum på ristet brød. Allergener: Hvete',
    image: 'bruschetta_tomat.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 50,
  },
  {
    productId: 25,
    categoryIndex: 1,
    productName: 'Blini med kaviar',
    unitPrice: 7.5,
    description: 'Liten blini toppet med kaviar og crème fraîche. Allergener: Melk, Hvete',
    image: 'blini_kaviar.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 20,
  },
  {
    productId: 26,
    categoryIndex: 1,
    productName: 'Minitoast med foie gras',
    unitPrice: 10.0,
    description: 'Eksklusiv canapé med foie gras og karamellisert løk på toast. Allergener: Hvete',
    image: 'minitoast_foiegras.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 10,
  },
  {
    productId: 27,
    categoryIndex: 1,
    productName: 'Agurkrull med røkelaks',
    unitPrice: 5.5,
    description: 'En frisk rull av agurk fylt med røkelaks og kremost. Allergener: Fisk, Melk',
    image: 'agurkrull_rokelaks.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 25,
  },
  {
    productId: 28,
    categoryIndex: 1,
    productName: 'Geitostkanapé',
    unitPrice: 4.5,
    description: 'Liten ristet brødskive med geitost og honning. Allergener: Melk, Hvete',
    image: 'geitostkanape.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 30,
  },
  {
    productId: 29,
    categoryIndex: 1,
    productName: 'Minipizza med chorizo',
    unitPrice: 6.0,
    description: 'En liten pizza med chorizo og mozzarella. Allergener: Melk, Hvete',
    image: 'minipizza_chorizo.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 20,
  },
  {
    productId: 30,
    categoryIndex: 1,
    productName: 'Mini-frittata med spinat',
    unitPrice: 4.0,
    description: 'En liten frittata laget med spinat og parmesan. Allergener: Egg, Melk',
    image: 'mini_frittata_spinat.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 35,
  },
  {
    productId: 31,
    categoryIndex: 1,
    productName: 'Ristet toast med avokado',
    unitPrice: 3.0,
    description: 'En lett canapé med most avokado og chiliflak. Allergener: Hvete',
    image: 'avokado_toast.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 50,
  },
  {
    productId: 32,
    categoryIndex: 1,
    productName: 'Tomat og mozzarella-bite',
    unitPrice: 4.5,
    description: 'En liten bite med fersk mozzarella og solmodne tomater. Allergener: Melk',
    image: 'tomat_mozzarella.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 40,
  },
  {
    productId: 33,
    categoryIndex: 1,
    productName: 'Mini tartar av oksekjøtt',
    unitPrice: 8.5,
    description: 'En liten porsjon tartar laget av mørt oksekjøtt og kapers. Allergener: Ingen',
    image: 'mini_tartar.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 15,
  },
  {
    productId: 34,
    categoryIndex: 1,
    productName: 'Mini toast med trøffel og sopp',
    unitPrice: 6.5,
    description: 'Toast med sautert sopp og trøffelolje. Allergener: Hvete',
    image: 'mini_truffel_toast.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 20,
  },
  {
    productId: 35,
    categoryIndex: 1,
    productName: 'Rødbete og geitostbiter',
    unitPrice: 4.5,
    description: 'Liten canapé med rødbete og kremet geitost. Allergener: Melk',
    image: 'rodbete_geitost.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 35,
  },
  {
    productId: 36,
    categoryIndex: 1,
    productName: 'Kamskjell med chili',
    unitPrice: 7.0,
    description: 'Ferske kamskjell med en touch av chili og lime. Allergener: Skalldyr',
    image: 'kamskjell_chili.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 20,
  },
  {
    productId: 37,
    categoryIndex: 1,
    productName: 'Mini rekeruller',
    unitPrice: 5.0,
    description: 'Friske rekeruller med rispapir og grønnsaker. Allergener: Skalldyr',
    image: 'mini_rekeruller.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 30,
  },
  {
    productId: 38,
    categoryIndex: 1,
    productName: 'Tunfisktartar på agurk',
    unitPrice: 6.5,
    description: 'Tunfisktartar servert på agurkskiver. Allergener: Fisk',
    image: 'tunfisk_tartar.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 15,
  },
  {
    productId: 39,
    categoryIndex: 1,
    productName: 'Prosciutto og melon',
    unitPrice: 5.5,
    description: 'Klassisk kombinasjon av prosciutto og melon. Allergener: Ingen',
    image: 'prosciutto_melon.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 50,
  },

  // Coffee Category (15 produkter)
  {
    productId: 40,
    categoryIndex: 2,
    productName: 'Espresso',
    unitPrice: 3.0,
    description: 'En intens og kraftig kopp espresso. Perfekt for en rask energiboost.',
    image: 'espresso.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 100,
  },
  {
    productId: 41,
    categoryIndex: 2,
    productName: 'Americano',
    unitPrice: 3.5,
    description: 'Espresso blandet med varmt vann for en mildere smak.',
    image: 'americano.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 100,
  },
  {
    productId: 42,
    categoryIndex: 2,
    productName: 'Cappuccino',
    unitPrice: 4.0,
    description: 'Kremet cappuccino med espresso og melkeskum. Allergener: Melk',
    image: 'cappuccino.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 80,
  },
  {
    productId: 43,
    categoryIndex: 2,
    productName: 'Latte',
    unitPrice: 4.5,
    description: 'En fyldig latte med steamet melk og espresso. Allergener: Melk',
    image: 'latte.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 80,
  },
  {
    productId: 44,
    categoryIndex: 2,
    productName: 'Cortado',
    unitPrice: 3.5,
    description: 'En balansert blanding av espresso og litt steamet melk. Allergener: Melk',
    image: 'cortado.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 60,
  },
  {
    productId: 45,
    categoryIndex: 2,
    productName: 'Macchiato',
    unitPrice: 3.5,
    description: 'Espresso toppet med en liten mengde melkeskum. Allergener: Melk',
    image: 'macchiato.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 70,
  },
  {
    productId: 46,
    categoryIndex: 2,
    productName: 'Mocha',
    unitPrice: 5.0,
    description: 'Latte med sjokoladesaus og espresso. Allergener: Melk',
    image: 'mocha.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 80,
  },
  {
    productId: 47,
    categoryIndex: 2,
    productName: 'Iskaffe',
    unitPrice: 4.5,
    description: 'Kald kaffe servert med isbiter og melk. Allergener: Melk',
    image: 'iskaffe.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 90,
  },
  {
    productId: 48,
    categoryIndex: 2,
    productName: 'Flat White',
    unitPrice: 4.5,
    description: 'En kremet kopp espresso med steamet melk. Allergener: Melk',
    image: 'flat_white.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 75,
  },
  {
    productId: 49,
    categoryIndex: 2,
    productName: 'Frappuccino',
    unitPrice: 5.5,
    description: 'En blendet iskaffe med krem og sjokoladesaus. Allergener: Melk',
    image: 'frappuccino.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 85,
  },
  {
    productId: 50,
    categoryIndex: 2,
    productName: 'Chai latte',
    unitPrice: 4.5,
    description: 'Latte laget med chai te og steamet melk. Allergener: Melk',
    image: 'chai_latte.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 70,
  },
  {
    productId: 51,
    categoryIndex: 2,
    productName: 'Affogato',
    unitPrice: 6.0,
    description: 'En dessert med espresso og vaniljeis. Allergener: Melk',
    image: 'affogato.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 40,
  },
  {
    productId: 52,
    categoryIndex: 2,
    productName: 'Iced Americano',
    unitPrice: 3.5,
    description: 'En kald versjon av Americano med isbiter.',
    image: 'iced_americano.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 90,
  },
  {
    productId: 53,
    categoryIndex: 2,
    productName: 'Karamell Macchiato',
    unitPrice: 5.0,
    description: 'En søt macchiato med karamellsaus. Allergener: Melk',
    image: 'karamell_macchiato.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 70,
  },
  {
    productId: 54,
    categoryIndex: 2,
    productName: 'Café au lait',
    unitPrice: 3.5,
    description: 'En klassisk blanding av kaffe og steamet melk. Allergener: Melk',
    image: 'cafe_au_lait.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 60,
  },

  // Cake Category (15 produkter)
  {
    productId: 55,
    categoryIndex: 3,
    productName: 'Sjokoladekake',
    unitPrice: 6.0,
    description: 'En rik og fyldig sjokoladekake med kremglasur. Allergener: Melk, Egg, Hvete',
    image: 'sjokoladekake.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 30,
  },
  {
    productId: 56,
    categoryIndex: 3,
    productName: 'Ostekake med bær',
    unitPrice: 7.0,
    description: 'En kremet ostekake toppet med friske bær. Allergener: Melk, Egg, Hvete',
    image: 'ostekake_baer.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 25,
  },
  {
    productId: 57,
    categoryIndex: 3,
    productName: 'Gulrotkake',
    unitPrice: 6.5,
    description: 'Saftig gulrotkake med kremostglasur. Allergener: Melk, Egg, Hvete',
    image: 'gulrotkake.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 35,
  },
  {
    productId: 58,
    categoryIndex: 3,
    productName: 'Red Velvet kake',
    unitPrice: 7.0,
    description: 'En elegant Red Velvet kake med kremostglasur. Allergener: Melk, Egg, Hvete',
    image: 'red_velvet.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 20,
  },
  {
    productId: 59,
    categoryIndex: 3,
    productName: 'Eplekake',
    unitPrice: 5.5,
    description: 'En klassisk eplekake med kanel og sukker. Allergener: Hvete, Egg',
    image: 'eplekake.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 40,
  },
  {
    productId: 60,
    categoryIndex: 3,
    productName: 'Sitronkake',
    unitPrice: 6.0,
    description: 'Frisk sitronkake med glasur. Allergener: Egg, Hvete',
    image: 'sitronkake.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 25,
  },
  {
    productId: 61,
    categoryIndex: 3,
    productName: 'Marmorkake',
    unitPrice: 5.5,
    description: 'En klassisk marmorkake med vanilje- og sjokoladesmak. Allergener: Melk, Egg, Hvete',
    image: 'marmorkake.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 30,
  },
  {
    productId: 62,
    categoryIndex: 3,
    productName: 'Cupcakes',
    unitPrice: 4.0,
    description: 'Dekorative cupcakes med smørkrem. Allergener: Melk, Egg, Hvete',
    image: 'cupcakes.webp',
    preorderRequired: true,
    customizationAvailable: true,
    unitsinStock: 50,
  },
  {
    productId: 63,
    categoryIndex: 3,
    productName: 'Brownies',
    unitPrice: 5.5,
    description: 'Seige brownies med sjokoladebiter. Allergener: Melk, Egg, Hvete',
    image: 'brownies.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 40,
  },
  {
    productId: 64,
    categoryIndex: 3,
    productName: 'Sjokolademousse',
    unitPrice: 6.5,
    description: 'En luftig sjokolademousse servert i glass. Allergener: Melk, Egg',
    image: 'sjokolademousse.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 20,
  },
  {
    productId: 65,
    categoryIndex: 3,
    productName: 'Frukttærte',
    unitPrice: 7.0,
    description: 'Sprø frukttærte med vaniljekrem og sesongens frukt. Allergener: Melk, Egg, Hvete',
    image: 'frukttaerte.webp',
    preorderRequired: false,
    customizationAvailable: false,
    unitsinStock: 30,
  },
  {
    productId: 66,
    categoryIndex: 3,
    productName: 'Makroner',
    unitPrice: 2.5,
    description: 'Franske makroner i ulike smaker. Allergener: Nøtter, Egg',
    image: 'makroner.webp',
    preorderRequired: true,
    customizationAvailable: true,
    unitsinStock: 100,
  },
  {
    productId: 67,
    categoryIndex: 3,
    productName: 'Tiramisu',
    unitPrice: 7.5,
    description: 'Klassisk italiensk dessert med mascarpone og kaffe. Allergener: Melk, Egg, Hvete',
    image: 'tiramisu.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 15,
  },
  {
    productId: 68,
    categoryIndex: 3,
    productName: 'Pavlova',
    unitPrice: 6.0,
    description: 'Luftig pavlova med krem og frukt. Allergener: Melk, Egg',
    image: 'pavlova.webp',
    preorderRequired: false,
    customizationAvailable: true,
    unitsinStock: 20,
  },
  {
    productId: 69,
    categoryIndex: 3,
    productName: 'Sjokoladefondant',
    unitPrice: 7.5,
    description: 'Varm sjokoladefondant med flytende kjerne. Allergener: Melk, Egg, Hvete',
    image: 'sjokoladefondant.webp',
    preorderRequired: true,
    customizationAvailable: false,
    unitsinStock: 10,
  },
];