name: Update README

on:
  workflow_run:
    workflows: ["Build and Deploy to GitHub Pages"]
    types:
      - completed
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create update script
        run: |
          cat > update-readme.js << 'EOF'
          const fs = require('fs');
          let content = fs.readFileSync('readme.md', 'utf8');

          // Update structure
          const structureUpdate = '#update_structure_start#\n' +
            '```\n' +
            require('child_process').execSync('tree -I "node_modules|dist|coverage|.git"').toString() +
            '```\n' +
            '#update_structure_end#';

          content = content.replace(
            /#update_structure_start#[\s\S]*?#update_structure_end#/,
            structureUpdate
          );

          // Architecture update with actual project structure
          const architectureUpdate = '#update_architecture_start#\n```mermaid\nflowchart TB\n' +
            '  subgraph Frontend["Browser Entry Points"]\n' +
            '    IndexHTML["index.html"]\n' +
            '    AdminHTML["admin/*.html"]\n' +
            '  end\n\n' +
            '  subgraph Core["Core System"]\n' +
            '    Model["model.js<br>- products[]<br>- orders[]<br>- app{}<br>- inputs{}"]\n' +
            '    BaseView["view.js<br>- updateView()<br>- createCurrentPageHtml()"]\n' +
            '    BaseController["controller.js<br>- switchMenu()"]\n' +
            '    Common["common.js<br>- getProductsForCategory()<br>- openProductInfo()"]\n' +
            '  end\n\n' +
            '  subgraph Products["Product Management"]\n' +
            '    CafeMenu["cafeMenuController.js<br>- switchTab()<br>- addToCart()"]\n' +
            '    CafeView["cafeMenuView.js"]\n' +
            '    CakeMenu["cakeMenuController.js"]\n' +
            '    CakeView["cakeMenuView.js"]\n' +
            '    ProductInv["productInventoryController.js"]\n' +
            '  end\n\n' +
            '  subgraph Cart["Shopping Cart"]\n' +
            '    CartCtrl["cartController.js"]\n' +
            '    CartView["cartView.js"]\n' +
            '    CheckoutCtrl["checkoutController.js"]\n' +
            '  end\n\n' +
            '  subgraph Admin["Admin System"]\n' +
            '    OrdersCtrl["ordersController.js"]\n' +
            '    OrdersView["ordersView.js"]\n' +
            '    Auth["authController.js"]\n' +
            '  end\n\n' +
            '  Core --> Products\n' +
            '  Core --> Cart\n' +
            '  Core --> Admin\n' +
            '  Frontend --> Core\n' +
            '```\n#update_architecture_end#\n';

          content = content.replace(
            /#update_architecture_start#[\s\S]*?#update_architecture_end#/,
            architectureUpdate
          );

          fs.writeFileSync('readme.md', content);
          EOF

      - name: Run update script
        run: node update-readme.js

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add readme.md
          git diff --staged --quiet || git commit -m "docs: update README"
          git push
