name: Update README

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create update script
        run: |
          cat > update-readme.js << 'EOF'
          const fs = require('fs');
          
          // Les eksisterende README
          let content = fs.readFileSync('README.md', 'utf8');
          
          // Oppdater prosjektstruktur
          const structureUpdate = `#update_structure_start#
\`\`\`
${require('child_process').execSync('tree -I "node_modules|dist|coverage|.git"').toString()}
\`\`\`
#update_structure_end#`;

          content = content.replace(
            /#update_structure_start#[\s\S]*?#update_structure_end#/,
            structureUpdate
          );

          // Oppdater arkitekturdiagram
          const architectureUpdate = `#update_architecture_start#
\`\`\`mermaid
flowchart TB
  subgraph Frontend["Browser Entry Points"]
    IndexHTML["index.html"]
    AdminHTML["admin/*.html"]
  end

  subgraph Core["Core System"]
    Model["model.js<br>- products[]<br>- orders[]<br>- app{}"]
    BaseView["view.js"]
    BaseController["controller.js"]
    Common["common.js"]
  end

  subgraph Components["Key Components"]
    Products["Products<br>- cafeMenu<br>- cakeMenu<br>- inventory"]
    Cart["Shopping Cart<br>- cart<br>- checkout"]
    Admin["Admin<br>- orders<br>- auth"]
  end

  Core --> Components
  Frontend --> Core
\`\`\`
#update_architecture_end#`;

          content = content.replace(
            /#update_architecture_start#[\s\S]*?#update_architecture_end#/,
            architectureUpdate
          );

          // Oppdater infrastruktur
          const infraUpdate = `#update_infrastructure_start#
\`\`\`mermaid
flowchart TB
  subgraph Build["Build System"]
    Gulp["gulp<br>- minify<br>- bundle<br>- deploy"]
    Babel["babel<br>transpilation"]
    ESLint["eslint + prettier"]
  end

  subgraph Runtime["Runtime"]
    SW["ServiceWorker<br>- caching<br>- offline"]
    LocalStorage["localStorage<br>- state<br>- cart"]
  end

  Build --> Runtime
\`\`\`
#update_infrastructure_end#`;

          content = content.replace(
            /#update_infrastructure_start#[\s\S]*?#update_infrastructure_end#/,
            infraUpdate
          );

          // Oppdater dokumentasjonslenker
          const docsUpdate = `#update_docs_start#
- [Full Komponent Dokumentasjon](src/docs/index.html)
- [Utviklingsoppsett](docs/development.md)
- [Bidragsretningslinjer](docs/contributing.md)
#update_docs_end#`;

          content = content.replace(
            /#update_docs_start#[\s\S]*?#update_docs_end#/,
            docsUpdate
          );

          fs.writeFileSync('README.md', content);
          EOF

      - name: Run update script
        run: node update-readme.js

      - name: Commit and Push README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "docs: update README sections" || echo "No changes to commit"
          git push
