name: Update README

on:
  workflow_run:
    workflows: ["Build and Deploy to GitHub Pages"]
    types:
      - completed
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create update script
        run: |
          cat > update-readme.js << 'EOF'
          const fs = require('fs');
          let content = fs.readFileSync('README.md', 'utf8');
          
          // Update structure
          const structureUpdate = '#update_structure_start#\n' +
            '```\n' +
            require('child_process').execSync('tree -I "node_modules|dist|coverage|.git"').toString() +
            '```\n' +
            '#update_structure_end#';
          
          content = content.replace(
            /#update_structure_start#[\s\S]*?#update_structure_end#/,
            structureUpdate
          );
          
          // Update architecture
          const architectureUpdate = '#update_architecture_start#\n' +
            '```mermaid\n' +
            'flowchart TB\n' +
            '  subgraph Frontend["Browser Entry Points"]\n' +
            '    IndexHTML["index.html"]\n' +
            '    AdminHTML["admin/*.html"]\n' +
            '  end\n\n' +
            '  subgraph Core["Core System"]\n' +
            '    Model["model.js"]\n' +
            '    BaseView["view.js"]\n' +
            '    BaseController["controller.js"]\n' +
            '    Common["common.js"]\n' +
            '  end\n\n' +
            '  subgraph Components["Key Components"]\n' +
            '    Products["Products"]\n' +
            '    Cart["Shopping Cart"]\n' +
            '    Admin["Admin"]\n' +
            '  end\n\n' +
            '  Core --> Components\n' +
            '  Frontend --> Core\n' +
            '```\n' +
            '#update_architecture_end#';
          
          content = content.replace(
            /#update_architecture_start#[\s\S]*?#update_architecture_end#/,
            architectureUpdate
          );
          
          fs.writeFileSync('README.md', content);
          EOF

      - name: Run update script
        run: node update-readme.js

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "docs: update README"
          git push
